name: maplestory

services:
  server:
    container_name: ms-server
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      # Login server
      - "8484:8484"
      # Channels.
      - "7575-7579:7575-7579"
    healthcheck:
      test: nc -z localhost 8484 || exit 1
      start_period: 60s
    restart: always
    volumes:
      - ../gms-server/scripts:/opt/server/scripts
      - ../gms-server/scripts-zh-CN:/opt/server/scripts-zh-CN
      - ../gms-server/wz:/opt/server/wz
      - ../gms-server/wz-zh-CN:/opt/server/wz-zh-CN
      - ../../beidou-server-config/application_docker_prod.yml:/opt/server/application.yml
      - ./logs:/opt/server/logs
  web:
    container_name: ms-web
    build:
      context: ../
      dockerfile: ./docker/web.Dockerfile
    healthcheck:
      test: nc -z localhost 80 || exit 1
    volumes:
      - ./nginx-ms-web.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8686:80"
    depends_on:
      server:
        condition: service_healthy